arch:
  - amd64
  - ppc64le
language: go

go:
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - tip
jobs:
 exclude:
  - go: 1.3
    arch: ppc64le
  - go: 1.4
    arch: ppc64le
  - go: 1.5
    arch: ppc64le
  - go: 1.6
    arch: ppc64le
  - go: 1.7
    arch: ppc64le
    
script: 
 - go test -v .
 - go test -v -race .
